apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: hetzner-lb-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        annotations:
          # This tells Hetzner where to put the LB
          load-balancer.hetzner.cloud/location: nbg1
          # Give it a name in the Hetzner Console
          load-balancer.hetzner.cloud/name: "fynncloud-lb-peak"
          # Use private IP for backend communication (faster/cheaper)
          load-balancer.hetzner.cloud/use-private-ip: "true"
