apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: fynncloud-image-updater
  namespace: argocd
spec:
  namespace: argocd

  commonUpdateSettings:
    updateStrategy: digest

  applicationRefs:
    - namePattern: "fynncloud"
      images:
        - alias: "fynncloud-web"
          imageName: "ghcr.io/fynncloudproject/web:latest"
          manifestTargets:
            helm:
              name: web.image.repository
              tag: web.image.tag
        - alias: "fynncloud-server"
          imageName: "ghcr.io/fynncloudproject/server:latest"
          manifestTargets:
            helm:
              name: backend.image.repository
              tag: backend.image.tag
