apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: fynncloud
  source:
    repoURL: https://github.com/thilojaeggi/FynnCloud-Argo.git
    path: infra/gateway
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
