apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imageupdater
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: fynncloud
  source:
    repoURL: https://github.com/thilojaeggi/FynnCloud-Argo.git
    path: infra/imageupdater
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: fynncloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
